name: 'ChangeSet Action'
description: 'A tool for make changes to file contents'
author: 'W4TR1X'
branding:
  icon: terminal
  color: purple
runs:
  using: 'node20'
  main: 'index.js'
inputs:
  dir:
    description:
      'The root directory to work from. Examples, "path/to/code".'
    required: false
    default: '/github/workspace'
  config:
    description:
      'The config file path. Defaults to ./changeset.config.json'
    required: false
    default: './changeset.config.json'
  pairs:
    description:
      'Value pairs'
    required: true
